import os
os.system("pip3 install --upgrade pip")
os.system("pip3 install sys")
os.system("pip3 install time")
os.system("pip3 install os")
os.system("pip3 install pxssh")
os.system("pip3 install optparse")
os.system("pip3 install smtplib")
os.system("pip3 install ftplibs")
os.system("pip3 install queue")
